---
kind: pipeline
name: branch

steps:
  - name: show environment
    image: node:10.16.3-jessie
    commands:
      - printenv

  - name: build and push image
    image: plugins/docker
    settings:
      repo: lbogdan/drone-example
      tags:
      - latest
      - ${DRONE_TAG}
      username: lbogdan
      password:
        from_secret: docker-password

trigger:
  # event: push
  # branch: main
  ref:
  - refs/tags/v*
---
kind: signature
hmac: 78ea1f776ae4426f9205ca0e325b0ef90a2e5995ce9c7e6ad865b0c9b66a30c5

...
