---
kind: pipeline
name: build

steps:
  - name: test plugin
    image: lbogdan/drone-deploy-plugin:v0.0.1
    settings:
      foo: bar
      foo-bar: baz
      ssh-key:
        from_secret: ssh-key

  # - name: build and push image
  #   image: plugins/docker
  #   settings:
  #     repo: lbogdan/drone-example
  #     tags:
  #     - latest
  #     - ${DRONE_TAG}
  #     username: lbogdan
  #     password:
  #       from_secret: docker-password

trigger:
  # event: push
  # branch: main
  ref:
    - refs/tags/v*
  event:
    exclude:
      - promote
---
kind: pipeline
name: deploy

steps:
  - name: show environment
    image: node:10.16.3-jessie
    commands:
      - printenv

trigger:
  event:
    - promote
---
kind: signature
hmac: ec5afa473a7c321dcf6bb2bb752b4321ebefe7a50be186bb091a8629e2e1b1f8

...
