---
kind: pipeline
name: branch

steps:
  - name: show environment
    image: node:10.16.3-jessie
    commands:
      - printenv

trigger:
  # event: push
  # branch: main
  ref:
  - refs/tags/v*
---
kind: signature
hmac: 9fcc1bd149694cc3c57cf9d4a15bade8e466afa448c059434a7c150c309b4e69

...
