---
kind: pipeline
name: build

steps:
  - name: test plugin
    image: lbogdan/drone-deploy-plugin:v0.0.1
    settings:
      foo: bar
      foo-bar: baz

  # - name: build and push image
  #   image: plugins/docker
  #   settings:
  #     repo: lbogdan/drone-example
  #     tags:
  #     - latest
  #     - ${DRONE_TAG}
  #     username: lbogdan
  #     password:
  #       from_secret: docker-password

trigger:
  # event: push
  # branch: main
  ref:
    - refs/tags/v*
  event:
    exclude:
      - promote
---
kind: pipeline
name: deploy

steps:
  - name: show environment
    image: node:10.16.3-jessie
    commands:
      - printenv

trigger:
  event:
    - promote
---
kind: signature
hmac: a58a381ead4e067729f509c0d3cdec713c1dc3284b5f9c7cdfa5e3188f14bb78

...
