---
kind: pipeline
name: branch

steps:
  - name: show environment
    image: node:10.16.3-jessie
    commands:
      - printenv

trigger:
  event: push
  branch: main
---
kind: signature
hmac: 1891e4aee3a93637f1b18b85f80fbc456fad32cea9e716c0b14a67c71de0e3b4

...
