---
kind: pipeline
name: build

steps:
  - name: show environment
    image: node:10.16.3-jessie
    commands:
      - printenv

  # - name: build and push image
  #   image: plugins/docker
  #   settings:
  #     repo: lbogdan/drone-example
  #     tags:
  #     - latest
  #     - ${DRONE_TAG}
  #     username: lbogdan
  #     password:
  #       from_secret: docker-password

trigger:
  # event: push
  # branch: main
  ref:
    - refs/tags/v*
  event:
    exclude:
      - promote
---
kind: pipeline
name: deploy

steps:
  - name: test deploy plugin
    image: lbogdan/drone-deploy-plugin:v0.0.3
    settings:
      app_name: example-app
      repo: lbogdan/test-test
      ssh_key:
        from_secret: ssh-key
      env: test

trigger:
  event:
    - promote
---
kind: signature
hmac: 6711902cb4c7a766afa3885135defd17ded77492c6bc6c9a04bac1eb217eabda

...
